### ISSUE TITLE
PEzor

### ISSUE THREAD

**Issue by xming-dot** [JustasMasiulis/inline_syscall#4]
https://iwantmore.pizza/posts/PEzor.html
I hava this problem 
T_T
T_T
T_T
In file included from test.cpp:2:
In file included from ./inline_syscall/include/in_memory_init.hpp:20:
In file included from ./inline_syscall/include/inline_syscall.hpp:103:
./inline_syscall/include/inline_syscall.inl:61:28: warning: inline variables are a C++17 extension [-Wc++17-extensions]
                "_sysc")]] inline static JM_INLINE_SYSCALL_ENTRY_TYPE entry{ Hash };
                           ^
In file included from test.cpp:2:
./inline_syscall/include/in_memory_init.hpp:178:62: error: use of undeclared identifier '__readgsqword'
            const auto peb = *reinterpret_cast<const char**>(__readgsqword(0x30) + 0x60);

**Comment by JustasMasiulis** [comment]
I personally don't really use mingw (and would highly recommend clang) so can't comment on why it doesn't work. I'd try these flags:
* `-fms-extensions` might add the intrinsic
* `-std=c++17` for that warning
* Double check that you aren't compiling for 32bit

Besides that 🤷 - `__readgsqword` should be in `<intrin.h>` which is included.

**Comment by xming-dot** [comment]
think you !

**Comment by xming-dot** [comment]
Thank you!

**Comment by JustasMasiulis** [comment]
I don't know if this issue is fixed, but I can't really help much if it's not a library issue.
